services:
  db:
    image: postgres:16-alpine
    container_name: local-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nomedobanco
    ports:
      - "5432:5432" #
    volumes:
      - ./pgdata:/var/lib/postgresql/data 

  pgadmin:
    image: dpage/pgadmin4
    container_name: local-pgadmin
    restart: always
    ports:
      - "8081:80"  
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin:/var/lib/pgadmin


  mailpit:
    image: axllent/mailpit:latest
    container_name: mono-mailpit
    ports:
      - "1025:1025" # Porta que o Spring vai usar para enviar e-mails
      - "8025:8025" # Porta que você vai abrir no navegador para ver os e-mails
    restart: always