server.port=8080
spring.application.name=mono-api

spring.ai.openai.api-key=${GROQ_API_KEY}
# Redireciona o Spring AI para a estrutura da Groq
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.1-8b-instant

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen2.5:0.5b


spring.datasource.url=jdbc:h2:mem:monodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123

# Permite que o Hibernate crie as tabelas automaticamente com base nas suas classes @Entity
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Ativa o Console Visual do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Desativa a proteção de frames para conseguir abrir o console do H2 com o Spring Security (se já tiver usando)
spring.ライフサイクル.spring.h2.console.settings.web-allow-others=true


jwt.secret=o_segredo_do_mono_precisa_ser_uma_chave_muito_longa_e_segura_123456
jwt.expiration=86400000