server.port=8080
spring.application.name=mono-api

spring.ai.openai.api-key=${GROQ_API_KEY}
# Redireciona o Spring AI para a estrutura da Groq
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=openai/gpt-oss-20b

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen2.5:0.5b

# URL de conexão com o banco que está rodando no Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/nomedobanco
spring.datasource.username=user
spring.datasource.password=password


app.encrypt-key=${KEY_BYTEA}

spring.datasource.hikari.connection-init-sql=SET app.encrypt_key = '${app.encrypt-key}';

# O Hibernate vai criar as tabelas automaticamente para você na primeira vez que rodar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


spring.h2.console.settings.web-allow-others=true


jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=3600000




spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=leonam253@gmail.com
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%5p) %clr([%X{requestId}]){cyan} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} : %m%n